### ISSUE TITLE
Track enrollment last offered

### ISSUE THREAD

**Issue by kevinhu** [coursetable/ferry#33]
Add computed fields in `courses` table tracking the `evaluation_statistics.enrolled` of the last time the course was offered (resolve by course codes) as well as the season and `course_id` of this last-enrolled date.

Planned fields:
- `courses.last_enrolled`
- `courses.last_enrolled_season`
- `courses.last_enrolled_course`

**Comment by hsheth2** [comment]
Maybe also add a field to if the last enrolled info is with the same professor or not

Will it be possible for the last enrolled data to come from the evals for that course itself (if it was something from 201903 for example?)

**Comment by kevinhu** [comment]
Yep, adding a field referencing if the last enrolled info is with the same professor is a good idea. 

I'm thinking of excluding the case where enrollment is for the course itself since we already provide that in `computed_listing_info`; the idea is this will be a fallback for when this is not available for current-season courses.
